language: node_js

node_js:
  - 14

cache: yarn

install:
  - yarn install --frozen-lockfile

script:
  - cross-env PUBLIC_PATH=/banana-ui/ yarn run docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  keep_history: true
  local_dir: docs-dist
  on:
    branch: master
